// Copyright 2025, University of Colorado Boulder
// AUTOMATICALLY GENERATED – DO NOT EDIT.
// Generated from membrane-transport-strings_en.yaml

/* eslint-disable */
/* @formatter:off */

import TReadOnlyProperty from '../../axon/js/TReadOnlyProperty.js';
import FluentPattern from '../../chipper/js/browser/FluentPattern.js';
import FluentContainer from '../../chipper/js/browser/FluentContainer.js';
import IntentionalAny from '../../phet-core/js/types/IntentionalAny.js';
import membraneTransport from './membraneTransport.js';
import MembraneTransportStrings from './MembraneTransportStrings.js';

const getFTL = (): string => {
  const ftl = `
membrane-transport.title = ${MembraneTransportStrings["membrane-transport"].titleStringProperty.value}
screen.simpleDiffusion = ${MembraneTransportStrings.screen.simpleDiffusionStringProperty.value}
screen.facilitatedDiffusion = ${MembraneTransportStrings.screen.facilitatedDiffusionStringProperty.value}
screen.activeTransport = ${MembraneTransportStrings.screen.activeTransportStringProperty.value}
screen.playground = ${MembraneTransportStrings.screen.playgroundStringProperty.value}
solutes = ${MembraneTransportStrings.solutesStringProperty.value}
oxygen = ${MembraneTransportStrings.oxygenStringProperty.value}
carbonDioxide = ${MembraneTransportStrings.carbonDioxideStringProperty.value}
sodiumIon = ${MembraneTransportStrings.sodiumIonStringProperty.value}
potassiumIon = ${MembraneTransportStrings.potassiumIonStringProperty.value}
glucose = ${MembraneTransportStrings.glucoseStringProperty.value}
atp = ${MembraneTransportStrings.atpStringProperty.value}
outside = ${MembraneTransportStrings.outsideStringProperty.value}
inside = ${MembraneTransportStrings.insideStringProperty.value}
membranePotentialLabels = ${MembraneTransportStrings.membranePotentialLabelsStringProperty.value}
voltageGatedChannels = ${MembraneTransportStrings.voltageGatedChannelsStringProperty.value}
ligandGatedChannels = ${MembraneTransportStrings.ligandGatedChannelsStringProperty.value}
activeTransporters = ${MembraneTransportStrings.activeTransportersStringProperty.value}
leakageChannels = ${MembraneTransportStrings.leakageChannelsStringProperty.value}
sodiumIonNaPlus = ${MembraneTransportStrings.sodiumIonNaPlusStringProperty.value}
potassiumIonKPlus = ${MembraneTransportStrings.potassiumIonKPlusStringProperty.value}
NaPlusKPlusPump = ${MembraneTransportStrings.NaPlusKPlusPumpStringProperty.value}
sodiumGlucoseCotransporter = ${MembraneTransportStrings.sodiumGlucoseCotransporterStringProperty.value}
membranePotential_mV = ${MembraneTransportStrings.membranePotential_mVStringProperty.value}
signs = ${MembraneTransportStrings.signsStringProperty.value}
addLigands = ${MembraneTransportStrings.addLigandsStringProperty.value}
removeLigands = ${MembraneTransportStrings.removeLigandsStringProperty.value}
animateLipids = ${MembraneTransportStrings.animateLipidsStringProperty.value}
animateLipidsDescription = ${MembraneTransportStrings.animateLipidsDescriptionStringProperty.value}
soluteConcentrations = ${MembraneTransportStrings.soluteConcentrationsStringProperty.value}
a11y_summary_playAreaSummaryIntro = ${MembraneTransportStrings.a11y.summary.playAreaSummaryIntroStringProperty.value}
a11y_summary_playAreaSummarySolutes = ${MembraneTransportStrings.a11y.summary.playAreaSummarySolutesStringProperty.value}
a11y_summary_playAreaSummaryProteins = ${MembraneTransportStrings.a11y.summary.playAreaSummaryProteinsStringProperty.value}
a11y_summary_playAreaSummaryPotential = ${MembraneTransportStrings.a11y.summary.playAreaSummaryPotentialStringProperty.value}
a11y_summary_playAreaSummaryBarCharts = ${MembraneTransportStrings.a11y.summary.playAreaSummaryBarChartsStringProperty.value}
a11y_summary_playAreaSummaryScreen1 = ${MembraneTransportStrings.a11y.summary.playAreaSummaryScreen1StringProperty.value}
a11y_summary_playAreaSummaryScreen2and4 = ${MembraneTransportStrings.a11y.summary.playAreaSummaryScreen2and4StringProperty.value}
a11y_summary_playAreaSummaryScreen3 = ${MembraneTransportStrings.a11y.summary.playAreaSummaryScreen3StringProperty.value}
a11y_summary_controlAreaSummary = ${MembraneTransportStrings.a11y.summary.controlAreaSummaryStringProperty.value}
a11y_summary_interactionHint = ${MembraneTransportStrings.a11y.summary.interactionHintStringProperty.value}
a11y_summary_interactionHintWithTransportProteins = ${MembraneTransportStrings.a11y.summary.interactionHintWithTransportProteinsStringProperty.value}
a11y_observationWindow_membrane_accessibleName = ${MembraneTransportStrings.a11y.observationWindow.membrane.accessibleNameStringProperty.value}
a11y_soluteControls_accessibleHeading = ${MembraneTransportStrings.a11y.soluteControls.accessibleHeadingStringProperty.value}
a11y_eraseSolutesButton_accessibleName = ${MembraneTransportStrings.a11y.eraseSolutesButton.accessibleNameStringProperty.value}
a11y_eraseSolutesButton_accessibleContextResponse = ${MembraneTransportStrings.a11y.eraseSolutesButton.accessibleContextResponseStringProperty.value}
a11y_transportProteinPanel_transportProteins = ${MembraneTransportStrings.a11y.transportProteinPanel.transportProteinsStringProperty.value}
a11y_transportProteinPanel_accessibleHelpText = ${MembraneTransportStrings.a11y.transportProteinPanel.accessibleHelpTextStringProperty.value}
a11y_transportProteinPanel_ligandGatedChannelPanel_sodiumIonNaPlusLigandGated = ${MembraneTransportStrings.a11y.transportProteinPanel.ligandGatedChannelPanel.sodiumIonNaPlusLigandGatedStringProperty.value}
a11y_transportProteinPanel_ligandGatedChannelPanel_potassiumIonKPlusLigandGated = ${MembraneTransportStrings.a11y.transportProteinPanel.ligandGatedChannelPanel.potassiumIonKPlusLigandGatedStringProperty.value}
a11y_transportProteinPanel_leakageChannelPanel_sodiumIonNaPlusLeakage = ${MembraneTransportStrings.a11y.transportProteinPanel.leakageChannelPanel.sodiumIonNaPlusLeakageStringProperty.value}
a11y_transportProteinPanel_leakageChannelPanel_potassiumIonKPlusLeakage = ${MembraneTransportStrings.a11y.transportProteinPanel.leakageChannelPanel.potassiumIonKPlusLeakageStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_sodiumIonNaPlusVoltageGated = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.sodiumIonNaPlusVoltageGatedStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_potassiumIonKPlusVoltageGated = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.potassiumIonKPlusVoltageGatedStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_membranePotential_radioButtonGroup_accessibleName = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.accessibleNameStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_membranePotential_radioButtonGroup_accessibleHelpText = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.accessibleHelpTextStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_membranePotential_radioButtonGroup_negative70RadioButton_accessibleName = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.negative70RadioButton.accessibleNameStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_membranePotential_radioButtonGroup_negative50RadioButton_accessibleName = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.negative50RadioButton.accessibleNameStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_membranePotential_radioButtonGroup_positive30RadioButton_accessibleName = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.positive30RadioButton.accessibleNameStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_signsCheckbox_accessibleHelpText = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.accessibleHelpTextStringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_signsCheckbox_checkedContextResponseNegative70 = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponseNegative70StringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_signsCheckbox_checkedContextResponseNegative50 = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponseNegative50StringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_signsCheckbox_checkedContextResponsePositive30 = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponsePositive30StringProperty.value}
a11y_transportProteinPanel_voltageGatedChannelPanel_signsCheckbox_uncheckedContextResponse = ${MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.uncheckedContextResponseStringProperty.value}
a11y_transportProteinPanel_activeTransportProteinPanel_sodiumPotassiumPump = ${MembraneTransportStrings.a11y.transportProteinPanel.activeTransportProteinPanel.sodiumPotassiumPumpStringProperty.value}
a11y_transportProteinPanel_activeTransportProteinPanel_sodiumGlucoseCotransporter = ${MembraneTransportStrings.a11y.transportProteinPanel.activeTransportProteinPanel.sodiumGlucoseCotransporterStringProperty.value}
a11y_transportProteinPanel_toolAccessibleHelpText = ${MembraneTransportStrings.a11y.transportProteinPanel.toolAccessibleHelpTextStringProperty.value}
a11y_ligandNode_starLigand = ${MembraneTransportStrings.a11y.ligandNode.starLigandStringProperty.value}
a11y_ligandNode_triangleLigand = ${MembraneTransportStrings.a11y.ligandNode.triangleLigandStringProperty.value}
a11y_ligandNode_accessibleHelpText = ${MembraneTransportStrings.a11y.ligandNode.accessibleHelpTextStringProperty.value}
a11y_ligandNode_releasedLigand = ${MembraneTransportStrings.a11y.ligandNode.releasedLigandStringProperty.value}
a11y_ligandNode_grabbedLigand = ${MembraneTransportStrings.a11y.ligandNode.grabbedLigandStringProperty.value}
a11y_ligandNode_ligandReleasedOffMembranePattern = ${MembraneTransportStrings.a11y.ligandNode.ligandReleasedOffMembranePatternStringProperty.value}
a11y_ligandNode_ligandReleasedOnProteinPattern = ${MembraneTransportStrings.a11y.ligandNode.ligandReleasedOnProteinPatternStringProperty.value}
a11y_ligandNode_ligandReleasedOnBusyOrIncompatibleProteinPattern = ${MembraneTransportStrings.a11y.ligandNode.ligandReleasedOnBusyOrIncompatibleProteinPatternStringProperty.value}
a11y_ligandNode_ligandMovedToSlotPattern = ${MembraneTransportStrings.a11y.ligandNode.ligandMovedToSlotPatternStringProperty.value}
a11y_ligandNode_ligandUnboundAlert = ${MembraneTransportStrings.a11y.ligandNode.ligandUnboundAlertStringProperty.value}
a11y_ligandNode_thereIsNoProteinAtThisSlot = ${MembraneTransportStrings.a11y.ligandNode.thereIsNoProteinAtThisSlotStringProperty.value}
a11y_ligandNode_thereIsProteinAtThisSlotPattern = ${MembraneTransportStrings.a11y.ligandNode.thereIsProteinAtThisSlotPatternStringProperty.value}
a11y_ligandNode_moveCancelledPattern = ${MembraneTransportStrings.a11y.ligandNode.moveCancelledPatternStringProperty.value}
a11y_ligandNode_cannotInteractWhileLigandIsBoundPattern = ${MembraneTransportStrings.a11y.ligandNode.cannotInteractWhileLigandIsBoundPatternStringProperty.value}
a11y_soluteControlsAccessibleHelpText = ${MembraneTransportStrings.a11y.soluteControlsAccessibleHelpTextStringProperty.value}
a11y_soluteAccessibleNames_oxygen = ${MembraneTransportStrings.a11y.soluteAccessibleNames.oxygenStringProperty.value}
a11y_soluteAccessibleNames_carbonDioxide = ${MembraneTransportStrings.a11y.soluteAccessibleNames.carbonDioxideStringProperty.value}
a11y_soluteAccessibleNames_sodiumIon = ${MembraneTransportStrings.a11y.soluteAccessibleNames.sodiumIonStringProperty.value}
a11y_soluteAccessibleNames_potassiumIon = ${MembraneTransportStrings.a11y.soluteAccessibleNames.potassiumIonStringProperty.value}
a11y_soluteAccessibleNames_glucose = ${MembraneTransportStrings.a11y.soluteAccessibleNames.glucoseStringProperty.value}
a11y_soluteAccessibleNames_atp = ${MembraneTransportStrings.a11y.soluteAccessibleNames.atpStringProperty.value}
a11y_outsideMembraneSpinnerAccessibleName = ${MembraneTransportStrings.a11y.outsideMembraneSpinnerAccessibleNameStringProperty.value}
a11y_outsideMembraneSpinnerHelpText = ${MembraneTransportStrings.a11y.outsideMembraneSpinnerHelpTextStringProperty.value}
a11y_insideMembraneSpinnerAccessibleName = ${MembraneTransportStrings.a11y.insideMembraneSpinnerAccessibleNameStringProperty.value}
a11y_insideMembraneSpinnerHelpText = ${MembraneTransportStrings.a11y.insideMembraneSpinnerHelpTextStringProperty.value}
a11y_soluteSpinnerRoleDescription = ${MembraneTransportStrings.a11y.soluteSpinnerRoleDescriptionStringProperty.value}
a11y_solute = ${MembraneTransportStrings.a11y.soluteStringProperty.value}
a11y_soluteSpinnerObjectResponsePattern = ${MembraneTransportStrings.a11y.soluteSpinnerObjectResponsePatternStringProperty.value}
a11y_soluteSpinnerContextResponsePattern = ${MembraneTransportStrings.a11y.soluteSpinnerContextResponsePatternStringProperty.value}
a11y_soluteBarChartsDescriptionParagraph = ${MembraneTransportStrings.a11y.soluteBarChartsDescriptionParagraphStringProperty.value}
a11y_arrowSizeDescription = ${MembraneTransportStrings.a11y.arrowSizeDescriptionStringProperty.value}
a11y_arrowDirectionDescription = ${MembraneTransportStrings.a11y.arrowDirectionDescriptionStringProperty.value}
a11y_barSizeDescription = ${MembraneTransportStrings.a11y.barSizeDescriptionStringProperty.value}
a11y_barChartPattern = ${MembraneTransportStrings.a11y.barChartPatternStringProperty.value}
a11y_currentDetailsActivityLevel = ${MembraneTransportStrings.a11y.currentDetailsActivityLevelStringProperty.value}
a11y_currentDetails = ${MembraneTransportStrings.a11y.currentDetailsStringProperty.value}
a11y_currentDetailsSoluteTypesOnOutside = ${MembraneTransportStrings.a11y.currentDetailsSoluteTypesOnOutsideStringProperty.value}
a11y_currentDetailsSoluteTypesOnInside = ${MembraneTransportStrings.a11y.currentDetailsSoluteTypesOnInsideStringProperty.value}
a11y_currentDetailsTransportProteins = ${MembraneTransportStrings.a11y.currentDetailsTransportProteinsStringProperty.value}
a11y_ligandsOnOutsideOnly = ${MembraneTransportStrings.a11y.ligandsOnOutsideOnlyStringProperty.value}
a11y_currentDetailsMembranePotential = ${MembraneTransportStrings.a11y.currentDetailsMembranePotentialStringProperty.value}
a11y_releasedBackInToolbox = ${MembraneTransportStrings.a11y.releasedBackInToolboxStringProperty.value}
a11y_selectedTransportProteinInSlot = ${MembraneTransportStrings.a11y.selectedTransportProteinInSlotStringProperty.value}
a11y_canceledBackInMembrane = ${MembraneTransportStrings.a11y.canceledBackInMembraneStringProperty.value}
a11y_grabbedProteinResponsePattern = ${MembraneTransportStrings.a11y.grabbedProteinResponsePatternStringProperty.value}
a11y_grabbedProteinResponseWithHintPattern = ${MembraneTransportStrings.a11y.grabbedProteinResponseWithHintPatternStringProperty.value}
a11y_ligandToggleButtonAccessibleHelpText = ${MembraneTransportStrings.a11y.ligandToggleButtonAccessibleHelpTextStringProperty.value}
a11y_ligandToggleButtonAddedContextResponse = ${MembraneTransportStrings.a11y.ligandToggleButtonAddedContextResponseStringProperty.value}
a11y_ligandToggleButtonRemovedContextResponse = ${MembraneTransportStrings.a11y.ligandToggleButtonRemovedContextResponseStringProperty.value}
a11y_grabbedLigandResponsePattern = ${MembraneTransportStrings.a11y.grabbedLigandResponsePatternStringProperty.value}
a11y_grabbedLigandResponseWithHintPattern = ${MembraneTransportStrings.a11y.grabbedLigandResponseWithHintPatternStringProperty.value}
a11y_grabbedLigandResponseWithEmptyMembraneHintPattern = ${MembraneTransportStrings.a11y.grabbedLigandResponseWithEmptyMembraneHintPatternStringProperty.value}
a11y_transportProteinBriefName = ${MembraneTransportStrings.a11y.transportProteinBriefNameStringProperty.value}
a11y_ligandMovedAboveLigandGatedChannelPattern = ${MembraneTransportStrings.a11y.ligandMovedAboveLigandGatedChannelPatternStringProperty.value}
a11y_ligandMovedAboveLeakageChannelPattern = ${MembraneTransportStrings.a11y.ligandMovedAboveLeakageChannelPatternStringProperty.value}
a11y_ligandMovedAboveOtherChannelPattern = ${MembraneTransportStrings.a11y.ligandMovedAboveOtherChannelPatternStringProperty.value}
a11y_transportProtein_accessibleNamePattern = ${MembraneTransportStrings.a11y.transportProtein.accessibleNamePatternStringProperty.value}
`;
  return ftl;
};

const allStringProperties = [
  MembraneTransportStrings["membrane-transport"].titleStringProperty,
MembraneTransportStrings.screen.simpleDiffusionStringProperty,
MembraneTransportStrings.screen.facilitatedDiffusionStringProperty,
MembraneTransportStrings.screen.activeTransportStringProperty,
MembraneTransportStrings.screen.playgroundStringProperty,
MembraneTransportStrings.solutesStringProperty,
MembraneTransportStrings.oxygenStringProperty,
MembraneTransportStrings.carbonDioxideStringProperty,
MembraneTransportStrings.sodiumIonStringProperty,
MembraneTransportStrings.potassiumIonStringProperty,
MembraneTransportStrings.glucoseStringProperty,
MembraneTransportStrings.atpStringProperty,
MembraneTransportStrings.outsideStringProperty,
MembraneTransportStrings.insideStringProperty,
MembraneTransportStrings.membranePotentialLabelsStringProperty,
MembraneTransportStrings.voltageGatedChannelsStringProperty,
MembraneTransportStrings.ligandGatedChannelsStringProperty,
MembraneTransportStrings.activeTransportersStringProperty,
MembraneTransportStrings.leakageChannelsStringProperty,
MembraneTransportStrings.sodiumIonNaPlusStringProperty,
MembraneTransportStrings.potassiumIonKPlusStringProperty,
MembraneTransportStrings.NaPlusKPlusPumpStringProperty,
MembraneTransportStrings.sodiumGlucoseCotransporterStringProperty,
MembraneTransportStrings.membranePotential_mVStringProperty,
MembraneTransportStrings.signsStringProperty,
MembraneTransportStrings.addLigandsStringProperty,
MembraneTransportStrings.removeLigandsStringProperty,
MembraneTransportStrings.animateLipidsStringProperty,
MembraneTransportStrings.animateLipidsDescriptionStringProperty,
MembraneTransportStrings.soluteConcentrationsStringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryIntroStringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummarySolutesStringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryProteinsStringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryPotentialStringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryBarChartsStringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryScreen1StringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryScreen2and4StringProperty,
MembraneTransportStrings.a11y.summary.playAreaSummaryScreen3StringProperty,
MembraneTransportStrings.a11y.summary.controlAreaSummaryStringProperty,
MembraneTransportStrings.a11y.summary.interactionHintStringProperty,
MembraneTransportStrings.a11y.summary.interactionHintWithTransportProteinsStringProperty,
MembraneTransportStrings.a11y.observationWindow.membrane.accessibleNameStringProperty,
MembraneTransportStrings.a11y.soluteControls.accessibleHeadingStringProperty,
MembraneTransportStrings.a11y.eraseSolutesButton.accessibleNameStringProperty,
MembraneTransportStrings.a11y.eraseSolutesButton.accessibleContextResponseStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.transportProteinsStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.accessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.ligandGatedChannelPanel.sodiumIonNaPlusLigandGatedStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.ligandGatedChannelPanel.potassiumIonKPlusLigandGatedStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.leakageChannelPanel.sodiumIonNaPlusLeakageStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.leakageChannelPanel.potassiumIonKPlusLeakageStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.sodiumIonNaPlusVoltageGatedStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.potassiumIonKPlusVoltageGatedStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.accessibleNameStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.accessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.negative70RadioButton.accessibleNameStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.negative50RadioButton.accessibleNameStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.positive30RadioButton.accessibleNameStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.accessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponseNegative70StringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponseNegative50StringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponsePositive30StringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.uncheckedContextResponseStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.activeTransportProteinPanel.sodiumPotassiumPumpStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.activeTransportProteinPanel.sodiumGlucoseCotransporterStringProperty,
MembraneTransportStrings.a11y.transportProteinPanel.toolAccessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.ligandNode.starLigandStringProperty,
MembraneTransportStrings.a11y.ligandNode.triangleLigandStringProperty,
MembraneTransportStrings.a11y.ligandNode.accessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.ligandNode.releasedLigandStringProperty,
MembraneTransportStrings.a11y.ligandNode.grabbedLigandStringProperty,
MembraneTransportStrings.a11y.ligandNode.ligandReleasedOffMembranePatternStringProperty,
MembraneTransportStrings.a11y.ligandNode.ligandReleasedOnProteinPatternStringProperty,
MembraneTransportStrings.a11y.ligandNode.ligandReleasedOnBusyOrIncompatibleProteinPatternStringProperty,
MembraneTransportStrings.a11y.ligandNode.ligandMovedToSlotPatternStringProperty,
MembraneTransportStrings.a11y.ligandNode.ligandUnboundAlertStringProperty,
MembraneTransportStrings.a11y.ligandNode.thereIsNoProteinAtThisSlotStringProperty,
MembraneTransportStrings.a11y.ligandNode.thereIsProteinAtThisSlotPatternStringProperty,
MembraneTransportStrings.a11y.ligandNode.moveCancelledPatternStringProperty,
MembraneTransportStrings.a11y.ligandNode.cannotInteractWhileLigandIsBoundPatternStringProperty,
MembraneTransportStrings.a11y.soluteControlsAccessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.soluteAccessibleNames.oxygenStringProperty,
MembraneTransportStrings.a11y.soluteAccessibleNames.carbonDioxideStringProperty,
MembraneTransportStrings.a11y.soluteAccessibleNames.sodiumIonStringProperty,
MembraneTransportStrings.a11y.soluteAccessibleNames.potassiumIonStringProperty,
MembraneTransportStrings.a11y.soluteAccessibleNames.glucoseStringProperty,
MembraneTransportStrings.a11y.soluteAccessibleNames.atpStringProperty,
MembraneTransportStrings.a11y.outsideMembraneSpinnerAccessibleNameStringProperty,
MembraneTransportStrings.a11y.outsideMembraneSpinnerHelpTextStringProperty,
MembraneTransportStrings.a11y.insideMembraneSpinnerAccessibleNameStringProperty,
MembraneTransportStrings.a11y.insideMembraneSpinnerHelpTextStringProperty,
MembraneTransportStrings.a11y.soluteSpinnerRoleDescriptionStringProperty,
MembraneTransportStrings.a11y.soluteStringProperty,
MembraneTransportStrings.a11y.soluteSpinnerObjectResponsePatternStringProperty,
MembraneTransportStrings.a11y.soluteSpinnerContextResponsePatternStringProperty,
MembraneTransportStrings.a11y.soluteBarChartsDescriptionParagraphStringProperty,
MembraneTransportStrings.a11y.arrowSizeDescriptionStringProperty,
MembraneTransportStrings.a11y.arrowDirectionDescriptionStringProperty,
MembraneTransportStrings.a11y.barSizeDescriptionStringProperty,
MembraneTransportStrings.a11y.barChartPatternStringProperty,
MembraneTransportStrings.a11y.currentDetailsActivityLevelStringProperty,
MembraneTransportStrings.a11y.currentDetailsStringProperty,
MembraneTransportStrings.a11y.currentDetailsSoluteTypesOnOutsideStringProperty,
MembraneTransportStrings.a11y.currentDetailsSoluteTypesOnInsideStringProperty,
MembraneTransportStrings.a11y.currentDetailsTransportProteinsStringProperty,
MembraneTransportStrings.a11y.ligandsOnOutsideOnlyStringProperty,
MembraneTransportStrings.a11y.currentDetailsMembranePotentialStringProperty,
MembraneTransportStrings.a11y.releasedBackInToolboxStringProperty,
MembraneTransportStrings.a11y.selectedTransportProteinInSlotStringProperty,
MembraneTransportStrings.a11y.canceledBackInMembraneStringProperty,
MembraneTransportStrings.a11y.grabbedProteinResponsePatternStringProperty,
MembraneTransportStrings.a11y.grabbedProteinResponseWithHintPatternStringProperty,
MembraneTransportStrings.a11y.ligandToggleButtonAccessibleHelpTextStringProperty,
MembraneTransportStrings.a11y.ligandToggleButtonAddedContextResponseStringProperty,
MembraneTransportStrings.a11y.ligandToggleButtonRemovedContextResponseStringProperty,
MembraneTransportStrings.a11y.grabbedLigandResponsePatternStringProperty,
MembraneTransportStrings.a11y.grabbedLigandResponseWithHintPatternStringProperty,
MembraneTransportStrings.a11y.grabbedLigandResponseWithEmptyMembraneHintPatternStringProperty,
MembraneTransportStrings.a11y.transportProteinBriefNameStringProperty,
MembraneTransportStrings.a11y.ligandMovedAboveLigandGatedChannelPatternStringProperty,
MembraneTransportStrings.a11y.ligandMovedAboveLeakageChannelPatternStringProperty,
MembraneTransportStrings.a11y.ligandMovedAboveOtherChannelPatternStringProperty,
MembraneTransportStrings.a11y.transportProtein.accessibleNamePatternStringProperty
];

const fluentSupport = new FluentContainer( getFTL, allStringProperties );

const MembraneTransportFluent = {
  "membrane-transport.titleStringProperty": MembraneTransportStrings["membrane-transport"].titleStringProperty,
  "screen.simpleDiffusionStringProperty": MembraneTransportStrings.screen.simpleDiffusionStringProperty,
  "screen.facilitatedDiffusionStringProperty": MembraneTransportStrings.screen.facilitatedDiffusionStringProperty,
  "screen.activeTransportStringProperty": MembraneTransportStrings.screen.activeTransportStringProperty,
  "screen.playgroundStringProperty": MembraneTransportStrings.screen.playgroundStringProperty,
  solutesStringProperty: MembraneTransportStrings.solutesStringProperty,
  oxygenStringProperty: MembraneTransportStrings.oxygenStringProperty,
  carbonDioxideStringProperty: MembraneTransportStrings.carbonDioxideStringProperty,
  sodiumIonStringProperty: MembraneTransportStrings.sodiumIonStringProperty,
  potassiumIonStringProperty: MembraneTransportStrings.potassiumIonStringProperty,
  glucoseStringProperty: MembraneTransportStrings.glucoseStringProperty,
  atpStringProperty: MembraneTransportStrings.atpStringProperty,
  outsideStringProperty: MembraneTransportStrings.outsideStringProperty,
  insideStringProperty: MembraneTransportStrings.insideStringProperty,
  membranePotentialLabelsStringProperty: MembraneTransportStrings.membranePotentialLabelsStringProperty,
  voltageGatedChannelsStringProperty: MembraneTransportStrings.voltageGatedChannelsStringProperty,
  ligandGatedChannelsStringProperty: MembraneTransportStrings.ligandGatedChannelsStringProperty,
  activeTransportersStringProperty: MembraneTransportStrings.activeTransportersStringProperty,
  leakageChannelsStringProperty: MembraneTransportStrings.leakageChannelsStringProperty,
  sodiumIonNaPlusStringProperty: MembraneTransportStrings.sodiumIonNaPlusStringProperty,
  potassiumIonKPlusStringProperty: MembraneTransportStrings.potassiumIonKPlusStringProperty,
  NaPlusKPlusPumpStringProperty: MembraneTransportStrings.NaPlusKPlusPumpStringProperty,
  sodiumGlucoseCotransporterStringProperty: MembraneTransportStrings.sodiumGlucoseCotransporterStringProperty,
  membranePotential_mVStringProperty: MembraneTransportStrings.membranePotential_mVStringProperty,
  signsStringProperty: MembraneTransportStrings.signsStringProperty,
  addLigandsStringProperty: MembraneTransportStrings.addLigandsStringProperty,
  removeLigandsStringProperty: MembraneTransportStrings.removeLigandsStringProperty,
  animateLipidsStringProperty: MembraneTransportStrings.animateLipidsStringProperty,
  animateLipidsDescriptionStringProperty: MembraneTransportStrings.animateLipidsDescriptionStringProperty,
  soluteConcentrationsStringProperty: MembraneTransportStrings.soluteConcentrationsStringProperty,
  a11y: {
    summary: {
      playAreaSummaryIntroStringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryIntroStringProperty,
      playAreaSummarySolutesStringProperty: MembraneTransportStrings.a11y.summary.playAreaSummarySolutesStringProperty,
      playAreaSummaryProteinsStringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryProteinsStringProperty,
      playAreaSummaryPotentialStringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryPotentialStringProperty,
      playAreaSummaryBarChartsStringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryBarChartsStringProperty,
      playAreaSummaryScreen1StringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryScreen1StringProperty,
      playAreaSummaryScreen2and4StringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryScreen2and4StringProperty,
      playAreaSummaryScreen3StringProperty: MembraneTransportStrings.a11y.summary.playAreaSummaryScreen3StringProperty,
      controlAreaSummaryStringProperty: MembraneTransportStrings.a11y.summary.controlAreaSummaryStringProperty,
      interactionHintStringProperty: MembraneTransportStrings.a11y.summary.interactionHintStringProperty,
      interactionHintWithTransportProteinsStringProperty: MembraneTransportStrings.a11y.summary.interactionHintWithTransportProteinsStringProperty
    },
    observationWindow: {
      membrane: {
        accessibleNameStringProperty: MembraneTransportStrings.a11y.observationWindow.membrane.accessibleNameStringProperty
      }
    },
    soluteControls: {
      accessibleHeadingStringProperty: MembraneTransportStrings.a11y.soluteControls.accessibleHeadingStringProperty
    },
    eraseSolutesButton: {
      accessibleNameStringProperty: MembraneTransportStrings.a11y.eraseSolutesButton.accessibleNameStringProperty,
      accessibleContextResponseStringProperty: MembraneTransportStrings.a11y.eraseSolutesButton.accessibleContextResponseStringProperty
    },
    transportProteinPanel: {
      transportProteinsStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.transportProteinsStringProperty,
      accessibleHelpTextStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.accessibleHelpTextStringProperty,
      ligandGatedChannelPanel: {
        sodiumIonNaPlusLigandGatedStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.ligandGatedChannelPanel.sodiumIonNaPlusLigandGatedStringProperty,
        potassiumIonKPlusLigandGatedStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.ligandGatedChannelPanel.potassiumIonKPlusLigandGatedStringProperty
      },
      leakageChannelPanel: {
        sodiumIonNaPlusLeakageStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.leakageChannelPanel.sodiumIonNaPlusLeakageStringProperty,
        potassiumIonKPlusLeakageStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.leakageChannelPanel.potassiumIonKPlusLeakageStringProperty
      },
      voltageGatedChannelPanel: {
        sodiumIonNaPlusVoltageGatedStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.sodiumIonNaPlusVoltageGatedStringProperty,
        potassiumIonKPlusVoltageGatedStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.potassiumIonKPlusVoltageGatedStringProperty,
        membranePotential: {
          radioButtonGroup: {
            accessibleNameStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.accessibleNameStringProperty,
            accessibleHelpTextStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.accessibleHelpTextStringProperty,
            negative70RadioButton: {
              accessibleNameStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.negative70RadioButton.accessibleNameStringProperty
            },
            negative50RadioButton: {
              accessibleNameStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.negative50RadioButton.accessibleNameStringProperty
            },
            positive30RadioButton: {
              accessibleNameStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.membranePotential.radioButtonGroup.positive30RadioButton.accessibleNameStringProperty
            }
          }
        },
        signsCheckbox: {
          accessibleHelpTextStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.accessibleHelpTextStringProperty,
          checkedContextResponseNegative70StringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponseNegative70StringProperty,
          checkedContextResponseNegative50StringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponseNegative50StringProperty,
          checkedContextResponsePositive30StringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.checkedContextResponsePositive30StringProperty,
          uncheckedContextResponseStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.voltageGatedChannelPanel.signsCheckbox.uncheckedContextResponseStringProperty
        }
      },
      activeTransportProteinPanel: {
        sodiumPotassiumPumpStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.activeTransportProteinPanel.sodiumPotassiumPumpStringProperty,
        sodiumGlucoseCotransporterStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.activeTransportProteinPanel.sodiumGlucoseCotransporterStringProperty
      },
      toolAccessibleHelpTextStringProperty: MembraneTransportStrings.a11y.transportProteinPanel.toolAccessibleHelpTextStringProperty
    },
    ligandNode: {
      starLigandStringProperty: MembraneTransportStrings.a11y.ligandNode.starLigandStringProperty,
      triangleLigandStringProperty: MembraneTransportStrings.a11y.ligandNode.triangleLigandStringProperty,
      accessibleHelpTextStringProperty: MembraneTransportStrings.a11y.ligandNode.accessibleHelpTextStringProperty,
      releasedLigandStringProperty: MembraneTransportStrings.a11y.ligandNode.releasedLigandStringProperty,
      grabbedLigandStringProperty: MembraneTransportStrings.a11y.ligandNode.grabbedLigandStringProperty,
      ligandReleasedOffMembranePatternStringProperty: MembraneTransportStrings.a11y.ligandNode.ligandReleasedOffMembranePatternStringProperty,
      ligandReleasedOnProteinPatternStringProperty: MembraneTransportStrings.a11y.ligandNode.ligandReleasedOnProteinPatternStringProperty,
      ligandReleasedOnBusyOrIncompatibleProteinPatternStringProperty: MembraneTransportStrings.a11y.ligandNode.ligandReleasedOnBusyOrIncompatibleProteinPatternStringProperty,
      ligandMovedToSlotPatternStringProperty: MembraneTransportStrings.a11y.ligandNode.ligandMovedToSlotPatternStringProperty,
      ligandUnboundAlertStringProperty: MembraneTransportStrings.a11y.ligandNode.ligandUnboundAlertStringProperty,
      thereIsNoProteinAtThisSlotStringProperty: MembraneTransportStrings.a11y.ligandNode.thereIsNoProteinAtThisSlotStringProperty,
      thereIsProteinAtThisSlotPatternStringProperty: MembraneTransportStrings.a11y.ligandNode.thereIsProteinAtThisSlotPatternStringProperty,
      moveCancelledPatternStringProperty: MembraneTransportStrings.a11y.ligandNode.moveCancelledPatternStringProperty,
      cannotInteractWhileLigandIsBoundPatternStringProperty: MembraneTransportStrings.a11y.ligandNode.cannotInteractWhileLigandIsBoundPatternStringProperty
    },
    soluteControlsAccessibleHelpTextStringProperty: MembraneTransportStrings.a11y.soluteControlsAccessibleHelpTextStringProperty,
    soluteAccessibleNames: {
      oxygenStringProperty: MembraneTransportStrings.a11y.soluteAccessibleNames.oxygenStringProperty,
      carbonDioxideStringProperty: MembraneTransportStrings.a11y.soluteAccessibleNames.carbonDioxideStringProperty,
      sodiumIonStringProperty: MembraneTransportStrings.a11y.soluteAccessibleNames.sodiumIonStringProperty,
      potassiumIonStringProperty: MembraneTransportStrings.a11y.soluteAccessibleNames.potassiumIonStringProperty,
      glucoseStringProperty: MembraneTransportStrings.a11y.soluteAccessibleNames.glucoseStringProperty,
      atpStringProperty: MembraneTransportStrings.a11y.soluteAccessibleNames.atpStringProperty
    },
    outsideMembraneSpinnerAccessibleNameStringProperty: MembraneTransportStrings.a11y.outsideMembraneSpinnerAccessibleNameStringProperty,
    outsideMembraneSpinnerHelpTextStringProperty: MembraneTransportStrings.a11y.outsideMembraneSpinnerHelpTextStringProperty,
    insideMembraneSpinnerAccessibleNameStringProperty: MembraneTransportStrings.a11y.insideMembraneSpinnerAccessibleNameStringProperty,
    insideMembraneSpinnerHelpTextStringProperty: MembraneTransportStrings.a11y.insideMembraneSpinnerHelpTextStringProperty,
    soluteSpinnerRoleDescriptionStringProperty: MembraneTransportStrings.a11y.soluteSpinnerRoleDescriptionStringProperty,
    solute: new FluentPattern<{ soluteType: 'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp' | TReadOnlyProperty<'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp'> }>( fluentSupport.bundleProperty, 'a11y_solute' ),
    soluteSpinnerObjectResponsePattern: new FluentPattern<{ amount: 'none' | 'one' | 'few' | 'some' | 'many' | TReadOnlyProperty<'none' | 'one' | 'few' | 'some' | 'many'>, soluteType: 'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp' | TReadOnlyProperty<'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp'> }>( fluentSupport.bundleProperty, 'a11y_soluteSpinnerObjectResponsePattern' ),
    soluteSpinnerContextResponsePattern: new FluentPattern<{ addedOrRemoved: 'added' | 'removed' | TReadOnlyProperty<'added' | 'removed'>, amount: 'aLittle' | 'aLot' | TReadOnlyProperty<'aLittle' | 'aLot'>, differenceSize: 'aLittle' | 'aLot' | TReadOnlyProperty<'aLittle' | 'aLot'>, directionality: 'insideThanOutside' | 'outsideThanInside' | TReadOnlyProperty<'insideThanOutside' | 'outsideThanInside'>, moreOrLessOrSame: 'same' | '*' | 'more' | 'less' | TReadOnlyProperty<'same' | '*' | 'more' | 'less'>, soluteType: 'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp' | TReadOnlyProperty<'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp'> }>( fluentSupport.bundleProperty, 'a11y_soluteSpinnerContextResponsePattern' ),
    soluteBarChartsDescriptionParagraphStringProperty: MembraneTransportStrings.a11y.soluteBarChartsDescriptionParagraphStringProperty,
    arrowSizeDescription: new FluentPattern<{ size: 'small' | 'medium' | 'large' | TReadOnlyProperty<'small' | 'medium' | 'large'> }>( fluentSupport.bundleProperty, 'a11y_arrowSizeDescription' ),
    arrowDirectionDescription: new FluentPattern<{ direction: 'upward' | 'downward' | TReadOnlyProperty<'upward' | 'downward'> }>( fluentSupport.bundleProperty, 'a11y_arrowDirectionDescription' ),
    barSizeDescription: new FluentPattern<{ amount: 'aLittleMore' | 'aLotMore' | 'aLittleLess' | 'aLotLess' | TReadOnlyProperty<'aLittleMore' | 'aLotMore' | 'aLittleLess' | 'aLotLess'> }>( fluentSupport.bundleProperty, 'a11y_barSizeDescription' ),
    barChartPattern: new FluentPattern<{ amount: 'aLittleMore' | 'aLotMore' | 'aLittleLess' | 'aLotLess' | TReadOnlyProperty<'aLittleMore' | 'aLotMore' | 'aLittleLess' | 'aLotLess'>, direction: 'upward' | 'downward' | TReadOnlyProperty<'upward' | 'downward'>, size: 'small' | 'medium' | 'large' | TReadOnlyProperty<'small' | 'medium' | 'large'>, soluteType: 'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp' | TReadOnlyProperty<'oxygen' | 'carbonDioxide' | 'sodiumIon' | 'potassiumIon' | 'glucose' | 'atp'> }>( fluentSupport.bundleProperty, 'a11y_barChartPattern' ),
    currentDetailsActivityLevel: new FluentPattern<{ activityLevel: 'calm' | 'active' | 'activeAndPaused' | TReadOnlyProperty<'calm' | 'active' | 'activeAndPaused'> }>( fluentSupport.bundleProperty, 'a11y_currentDetailsActivityLevel' ),
    currentDetails: new FluentPattern<{ activityLevel: 'calm' | 'active' | 'activeAndPaused' | TReadOnlyProperty<'calm' | 'active' | 'activeAndPaused'> }>( fluentSupport.bundleProperty, 'a11y_currentDetails' ),
    currentDetailsSoluteTypesOnOutside: new FluentPattern<{ outsideSoluteCount: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_currentDetailsSoluteTypesOnOutside' ),
    currentDetailsSoluteTypesOnInside: new FluentPattern<{ insideSoluteCount: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_currentDetailsSoluteTypesOnInside' ),
    currentDetailsTransportProteins: new FluentPattern<{ transportProteinCount: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_currentDetailsTransportProteins' ),
    ligandsOnOutsideOnlyStringProperty: MembraneTransportStrings.a11y.ligandsOnOutsideOnlyStringProperty,
    currentDetailsMembranePotential: new FluentPattern<{ membranePotential: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_currentDetailsMembranePotential' ),
    releasedBackInToolboxStringProperty: MembraneTransportStrings.a11y.releasedBackInToolboxStringProperty,
    selectedTransportProteinInSlot: new FluentPattern<{ channelName: IntentionalAny, slotCount: IntentionalAny, slotIndex: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_selectedTransportProteinInSlot' ),
    canceledBackInMembraneStringProperty: MembraneTransportStrings.a11y.canceledBackInMembraneStringProperty,
    grabbedProteinResponsePattern: new FluentPattern<{ slotCount: IntentionalAny, slotIndex: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_grabbedProteinResponsePattern' ),
    grabbedProteinResponseWithHintPattern: new FluentPattern<{ slotCount: IntentionalAny, slotIndex: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_grabbedProteinResponseWithHintPattern' ),
    ligandToggleButtonAccessibleHelpTextStringProperty: MembraneTransportStrings.a11y.ligandToggleButtonAccessibleHelpTextStringProperty,
    ligandToggleButtonAddedContextResponseStringProperty: MembraneTransportStrings.a11y.ligandToggleButtonAddedContextResponseStringProperty,
    ligandToggleButtonRemovedContextResponseStringProperty: MembraneTransportStrings.a11y.ligandToggleButtonRemovedContextResponseStringProperty,
    grabbedLigandResponsePattern: new FluentPattern<{ proteinCount: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_grabbedLigandResponsePattern' ),
    grabbedLigandResponseWithHintPattern: new FluentPattern<{ proteinCount: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_grabbedLigandResponseWithHintPattern' ),
    grabbedLigandResponseWithEmptyMembraneHintPattern: new FluentPattern<{ proteinCount: IntentionalAny }>( fluentSupport.bundleProperty, 'a11y_grabbedLigandResponseWithEmptyMembraneHintPattern' ),
    transportProteinBriefName: new FluentPattern<{ type: 'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter' | TReadOnlyProperty<'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter'> }>( fluentSupport.bundleProperty, 'a11y_transportProteinBriefName' ),
    ligandMovedAboveLigandGatedChannelPattern: new FluentPattern<{ index: IntentionalAny, ligandType: 'triangleLigand' | 'starLigand' | TReadOnlyProperty<'triangleLigand' | 'starLigand'>, openOrClosed: 'open' | 'closed' | TReadOnlyProperty<'open' | 'closed'>, transportProteinCount: IntentionalAny, type: 'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter' | TReadOnlyProperty<'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter'> }>( fluentSupport.bundleProperty, 'a11y_ligandMovedAboveLigandGatedChannelPattern' ),
    ligandMovedAboveLeakageChannelPattern: new FluentPattern<{ index: IntentionalAny, transportProteinCount: IntentionalAny, type: 'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter' | TReadOnlyProperty<'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter'> }>( fluentSupport.bundleProperty, 'a11y_ligandMovedAboveLeakageChannelPattern' ),
    ligandMovedAboveOtherChannelPattern: new FluentPattern<{ index: IntentionalAny, openOrClosed: 'open' | 'closed' | TReadOnlyProperty<'open' | 'closed'>, transportProteinCount: IntentionalAny, type: 'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter' | TReadOnlyProperty<'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter'> }>( fluentSupport.bundleProperty, 'a11y_ligandMovedAboveOtherChannelPattern' ),
    transportProtein: {
      accessibleNamePattern: new FluentPattern<{ openOrClosed: 'open' | 'closed' | TReadOnlyProperty<'open' | 'closed'>, proteinCount: IntentionalAny, proteinIndex: IntentionalAny, type: 'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter' | TReadOnlyProperty<'sodiumIonLeakageChannel' | 'potassiumIonLeakageChannel' | 'sodiumIonVoltageGatedChannel' | 'potassiumIonVoltageGatedChannel' | 'sodiumIonLigandGatedChannel' | 'potassiumIonLigandGatedChannel' | 'sodiumPotassiumPump' | 'sodiumGlucoseCotransporter'> }>( fluentSupport.bundleProperty, 'a11y_transportProtein_accessibleNamePattern' )
    }
  }
};

export default MembraneTransportFluent;

membraneTransport.register('MembraneTransportFluent', MembraneTransportFluent);
